[package]
name = "ghs_demangle"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "7.1.1"
clap = "3.2.17"
once_cell = "1.13.1"